### ISSUE TITLE
Change suggestions

### ISSUE THREAD

**Issue by helderco** [mkoistinen/cmsplugin-sections#1]
Hey, I'm doing a set of changes to this plugin. I can extend your base classes in my own app or I can PR some of these to you:
- Internationalize app (gettext);
- Add setting to section container to include prev/next links;
- Add setting to section container to include menu;
- Add plugin that renders menu (allows placing menu in separate placeholder independently);
- Break `section-container.html` into partials to override less;
- Provide to template all sections, not just the ones in menu (otherwise `sections.0.section_menu_slug` may not work as expected);
- Better default HTML5 tags (i.e., `<main>` instead of `<div>` for main content and `<article>` instead of `<section>` for section content?

What do you think?

**Comment by mkoistinen** [comment]
+1!

**Comment by helderco** [comment]
How can I have a field in a plugin that allows me to choose from another plugin in the current page?

I want to have a "Sections Menu Plugin" that allows me to select a container plugin from the current page. Is there a better way to render the menu separately?

**Comment by helderco** [comment]
I've chosen the approach used by the Alias plugin, where you create a menu plugin from the contextual menu of a sections container plugin in structure mode. It's working now :)

**Comment by helderco** [comment]
What's the `subordinate_page` for in `SectionContainerPluginModel`?

**Comment by mkoistinen** [comment]
That option allows you to treat "subordinate pages" (i.e., not the front page) differently. When I started this project, it was for a project that was supposed to be a single page, but then, over time, it required multiple pages, and I needed a way to tell this app to treat non-front pages differently is all.

**Comment by helderco** [comment]
Ok, since nothing in the app used it I removed it. Maybe it can go into an extension if it's needed? `SectionContainerPlugin` was using `CMSPlugin` as model, but I changed it to `SectionContainerPluginModel` so I could target these plugin types (with isinstance).
